#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces
# shellcheck disable=SC2034

# Image source — SmartPi One (AllWinner H3, armhf, Debian 12 Bookworm)
DOWNLOAD_URL_CHECKSUM="${DOWNLOAD_BASE_URL}/Yumi-smartpi1-bookworm-debian12-server-2026-03-01-2139.img.xz.sha256"
DOWNLOAD_URL_IMAGE="${DOWNLOAD_BASE_URL}/Yumi-smartpi1-bookworm-debian12-server-2026-03-01-2139.img.xz"

BASE_IMAGE_ENLARGEROOT=3000
MODULES="base(udev_fix,armbian(armbian_net,yumios,minecraft,pumpkin,pufferpanel))"

# export Variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
