#!/usr/bin/env bash
# Shebang for better file detection
#### YUMIOS module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2024
####
#### This File is distributed under GPLv3
####

#### NOTE:
#### Minimal toolset for Minecraft server diagnostics

[ -n "$YUMIOS_DEPS" ] || YUMIOS_DEPS="htop nano usbutils ncdu lsof"
